### ISSUE TITLE
Errror importing swagger_client Python module

### ISSUE THREAD

**Issue by fmussi** [ni/systemlink-OpenAPI-documents#20]
Steps done: 
1) Generated pyhon client  from tag.yml -> Ok
2) installed on Debian machine with python3 ('3.5.3 (default, Sep 27 2018, 17:25:39) \n[GCC 6.3.0 20170516]')
2.1 -> unzip python-client-generated.zip
2.2 -> pip install python-client
3) when I run python and import swagger_client, get this error

/usr/bin/python3.5 /home/fmussi/atomProjs/sandbox/skyline/test_SMSapi_swagger.py
Traceback (most recent call last):
  File "/home/fmussi/atomProjs/sandbox/skyline/test_SMSapi_swagger.py", line 3, in <module>
    import swagger_client
  File "/home/fmussi/.local/lib/python3.5/site-packages/swagger_client/__init__.py", line 19, in <module>
    from swagger_client.api.selections_api import SelectionsApi
  File "/home/fmussi/.local/lib/python3.5/site-packages/swagger_client/api/__init__.py", line 6, in <module>
    from swagger_client.api.selections_api import SelectionsApi
  File "/home/fmussi/.local/lib/python3.5/site-packages/swagger_client/api/selections_api.py", line 21, in <module>
    from swagger_client.api_client import ApiClient
  File "/home/fmussi/.local/lib/python3.5/site-packages/swagger_client/api_client.py", line 27, in <module>
    import swagger_client.models
  File "/home/fmussi/.local/lib/python3.5/site-packages/swagger_client/models/__init__.py", line 20, in <module>
    from swagger_client.models.error import Error
  File "/home/fmussi/.local/lib/python3.5/site-packages/swagger_client/models/error.py", line 19, in <module>
    from swagger_client.models.error import Error  # noqa: F401,E501
ImportError: cannot import name 'Error'

Process finished with exit code 1

**Comment by spanglerco** [comment]
This is an issue in the swagger-codegen for Python: https://github.com/swagger-api/swagger-codegen/issues/7541. The Error model recursively references itself, and the Python client codegen is trying to import itself. There appears to be a pull request up to fix it, but it hasn't had any activity in a few months.
